# Generated by Django 4.2.1 on 2023-05-25 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel_order', 'The User can cancel order')]},
        ),
    ]
